[project]
name = "espnet"
dynamic = ["version", "readme"]
authors = [
    {name="Shinji Watanabe", email="shinjiw@ieee.org"}
]
description = "ESPnet: end-to-end speech processing toolkit"
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Science/Research",
    "Operating System :: POSIX :: Linux",
    "License :: OSI Approved :: Apache Software License",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
requires-python = ">=3.10"
license = { "text" = "Apache Software License" }
dependencies = [
    "setuptools>=38.5.1,<74.0.0",
    "configargparse>=1.2.1",
    "packaging",
    "typeguard",
    "humanfriendly",
    "scipy>=1.4.1",
    "numpy<1.24",
    "PyYAML>=5.1.2",
    "soundfile>=0.10.2",
    "torch>=1.11.0",
    "torchaudio>=1.11.0",
    "soundfile>=0.10.2",
    "kaldiio>=2.18.0",
    "sentencepiece==0.2.0",
    "librosa>0.9.2",
    "lightning",
    "torch_complex",
    "tensorboard",
    "einops",
    "lhotse",
    "espnet_model_zoo",
    "matplotlib",
    "nltk>=3.4.5",
]

[project.urls]
Homepage = "http://github.com/espnet/espnet"

[build-system]
requires = ["setuptools>=38.5.1,<74.0.0", "wheel", "setuptools-scm>=8.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
version = {attr = "espnet.__version__"}
readme = {file = ["README.md"], content-type = "text/markdown"}

[tool.setuptools.packages.find]
include = ["espnet*"]

[tool.setuptools.package-data]
espnet = ["version.txt"]

[project.optional-dependencies]

espnet-3 = [
  "hydra-core",
  "omegaconf",
  "datasets",
  "dask[distributed]",
  "dask_jobqueue",
]

task-asr = [
  "ctc-segmentation>=1.6.6",
  "editdistance",
  "hydra-core",
  "omegaconf",
  "opt_einsum",
]

task-tts = [
  "pyworld>=0.3.4",
  "pypinyin<=0.44.0",
  "espnet_tts_frontend",
  "g2p_en",
  "jamo",
  "jaconv",
  "underthesea",
]

task-enh = [
  "ci_sdr",
  "fast-bss-eval==0.1.3"
]

task-asr2 = [
  "editdistance",
]

task-s2st = [
  "editdistance",
  "s3prl",
]

task-st = [
  "editdistance",
]

task-s2t = [
  "editdistance",
]

task-spk = [
  "asteroid_filterbanks==0.4.0"
]

dev = [
  "black",
  "flake8",
  "pytest",
  "pytest-cov",
  "isort"
]

test = [
  "pytest>=7.0.0",
  "pytest-timeouts>=1.2.1",
  "pytest-pythonpath>=0.7.3",
  "pytest-cov>=2.7.1",
  "hacking>=2.0.0",
  "mock>=2.0.0",
  "pycodestyle",
  "jsondiff>=2.0.0",
  "flake8>=3.7.8",
  "flake8-docstrings>=1.3.1",
  "black",
  "isort",
  "h5py",
]

doc = [
  "sphinx",
  "sphinx-rtd-theme",
  "myst-parser",
  "sphinx-argparse",
  "sphinx-markdown-builder"
]

all = [
  "espnet[task-asr]",
  "espnet[task-tts]",
  "espnet[task-enh]",
  "espnet[task-spk]",
  "torchaudio",
  "torch_optimizer",
  "fairscale",
  "transformers",
  "evaluate",
]
