# MARCC setup
command sbatch --export=PATH,LD_LIBRARY_PATH,LIBRARY_PATH
option gpu=* -p gpu --gres=gpu:$0 --time 24:0:0
option mem=* --mem-per-cpu $0
option num_threads=* --cpus-per-task $0
option ntasks-per-node=*
option mail-type=end
option mail-user=nyalta1@jhu.edu
