# Default configuration
command sbatch --export=PATH,LD_LIBRARY_PATH,LIBRARY_PATH
option mem=* --mem-per-cpu $0 --time 48:0:0
option num_threads=* --cpus-per-task $0
option ntasks-per-node=*
option mail-type=end
option mail-user=nyalta1@jhu.edu